import React,{useMemo,useState}from'react';import{ActivityIndicator,Image,Pressable,SafeAreaView,ScrollView,StatusBar,StyleSheet,Text,TextInput,View}from'react-native';
const C={bg:'#F7F5F0',white:'#FFF',ink:'#121212',muted:'#77736C',line:'#E7E3DC',red:'#C92B2B',soft:'#F0ECE5'};
const cats=['Para você','Brasil','Mundo','Tecnologia','Ciência','Economia','Cultura'];
const news=[
{id:'1',cat:'Tecnologia',title:'A nova fase da inteligência artificial está mudando a forma de trabalhar',desc:'Empresas estão colocando agentes e automações no centro de operações reais.',img:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=85',time:'8 min'},
{id:'2',cat:'Brasil',title:'Cidades aceleram projetos para modernizar serviços públicos',desc:'Novas iniciativas apostam em dados, digitalização e atendimento mais simples.',img:'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=900&q=85',time:'5 min'},
{id:'3',cat:'Ciência',title:'Pesquisadores encontram novas pistas sobre como o cérebro aprende',desc:'Estudo reforça a importância das conexões entre atenção, memória e repetição.',img:'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?auto=format&fit=crop&w=900&q=85',time:'6 min'},
{id:'4',cat:'Mundo',title:'O que está acontecendo na economia global nesta semana',desc:'Mercados acompanham juros, inflação e novos indicadores de atividade.',img:'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&w=900&q=85',time:'7 min'},
{id:'5',cat:'Cultura',title:'A cultura digital está criando novas formas de contar histórias',desc:'Criadores misturam vídeo, texto e experiências interativas.',img:'https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&w=900&q=85',time:'4 min'}];
const Logo=()=> <View style={s.logoRow}><View style={s.mark}><Text style={s.markText}>P</Text></View><Text style={s.logo}>PAM</Text></View>;
const Heart=({active,onPress})=><Pressable onPress={onPress} style={s.heart}><Text style={{fontSize:22,color:active?C.red:C.ink}}>{active?'♥':'♡'}</Text></Pressable>;

function Login({onLogin}){const[signup,setSignup]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[err,setErr]=useState(''),[loading,setLoading]=useState(false);const submit=()=>{setErr('');if(signup&&name.trim().length<2)return setErr('Digite seu nome.');if(!email.includes('@'))return setErr('Digite um e-mail válido.');if(pass.length<6)return setErr('A senha precisa ter 6 caracteres ou mais.');setLoading(true);setTimeout(()=>{setLoading(false);onLogin({name:name.trim()||email.split('@')[0],email})},500)};return <SafeAreaView style={s.login}><StatusBar barStyle="dark-content"/><ScrollView contentContainerStyle={s.loginBox}><Logo/><Text style={s.kicker}>NOTÍCIAS, SEM RUÍDO</Text><Text style={s.loginTitle}>{signup?'Crie sua conta.':'Entre na sua conta.'}</Text><Text style={s.loginDesc}>{signup?'Salve matérias e monte seu próprio feed.':'Acompanhe as notícias que importam para você.'}</Text><View style={s.form}>{signup&&<TextInput value={name} onChangeText={setName} placeholder="Seu nome" placeholderTextColor="#999" style={s.input}/>}<TextInput value={email} onChangeText={setEmail} placeholder="E-mail" placeholderTextColor="#999" style={s.input} keyboardType="email-address" autoCapitalize="none"/><TextInput value={pass} onChangeText={setPass} placeholder="Senha" placeholderTextColor="#999" style={s.input} secureTextEntry/>{!!err&&<Text style={s.error}>{err}</Text>}<Pressable onPress={submit} disabled={loading} style={s.primary}>{loading?<ActivityIndicator color="#fff"/>:<Text style={s.primaryText}>{signup?'Criar conta':'Entrar'}</Text>}</Pressable><Pressable onPress={()=>{setSignup(!signup);setErr('')}} style={s.switch}><Text style={s.switchText}>{signup?'Já tenho uma conta':'Ainda não tenho uma conta'}</Text></Pressable></View><Text style={s.note}>Protótipo local de autenticação. O backend real pode ser conectado depois.</Text></ScrollView></SafeAreaView>}

function Tabs({tab,setTab}){const items=[['home','Início','⌂'],['search','Buscar','⌕'],['saved','Salvos','♡'],['profile','Perfil','◉']];return <View style={s.tabs}>{items.map(([k,l,i])=><Pressable key={k} onPress={()=>setTab(k)} style={s.tab}><Text style={[s.tabIcon,tab===k&&s.active]}>{i}</Text><Text style={[s.tabLabel,tab===k&&s.active]}>{l}</Text></Pressable>)}</View>}

function Home({user,saved,toggle,open,cat,setCat}){const list=cat==='Para você'?news:news.filter(a=>a.cat===cat);return <SafeAreaView style={s.root}><StatusBar barStyle="dark-content"/><ScrollView contentContainerStyle={s.page}><View style={s.header}><View><Text style={s.greet}>Bom dia, {user.name.split(' ')[0]}.</Text><Text style={s.headerTitle}>O que está acontecendo?</Text></View><Logo/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{cats.map(x=><Pressable key={x} onPress={()=>setCat(x)} style={[s.chip,cat===x&&s.chipOn]}><Text style={[s.chipText,cat===x&&s.chipTextOn]}>{x}</Text></Pressable>)}</ScrollView>{list[0]&&<Pressable onPress={()=>open(list[0])} style={s.hero}><Image source={{uri:list[0].img}} style={s.heroImg}/><View style={s.overlay}/><View style={s.heroText}><Text style={s.eyebrowLight}>{list[0].cat.toUpperCase()}</Text><Text style={s.heroTitle}>{list[0].title}</Text><Text style={s.heroDesc}>{list[0].desc}</Text><Text style={s.timeLight}>{list[0].time} de leitura</Text></View><View style={s.heroHeart}><Heart active={saved.includes(list[0].id)} onPress={()=>toggle(list[0].id)}/></View></Pressable>}<View style={s.section}><Text style={s.sectionTitle}>Mais recentes</Text><Text style={s.muted}>{list.length} matérias</Text></View>{list.slice(1).map(a=><Pressable key={a.id} onPress={()=>open(a)} style={s.card}><Image source={{uri:a.img}} style={s.cardImg}/><View style={s.cardBody}><Text style={s.eyebrow}>{a.cat.toUpperCase()}</Text><Text style={s.cardTitle}>{a.title}</Text><Text style={s.cardDesc} numberOfLines={2}>{a.desc}</Text><Text style={s.time}>{a.time} de leitura</Text></View><Heart active={saved.includes(a.id)} onPress={()=>toggle(a.id)}/></Pressable>)}</ScrollView></SafeAreaView>}

function Search({open}){const[q,setQ]=useState('');const result=useMemo(()=>{const x=q.trim().toLowerCase();return x?news.filter(a=>(a.title+' '+a.desc+' '+a.cat).toLowerCase().includes(x)):news},[q]);return <SafeAreaView style={s.root}><StatusBar barStyle="dark-content"/><ScrollView contentContainerStyle={s.page}><Text style={s.screenTitle}>Buscar</Text><View style={s.search}><Text style={s.searchIcon}>⌕</Text><TextInput value={q} onChangeText={setQ} placeholder="Buscar notícias" placeholderTextColor="#999" style={s.searchInput}/></View><Text style={s.sectionTitle}>{q?result.length+' resultado(s)':'Em destaque'}</Text>{result.map(a=><Pressable key={a.id} onPress={()=>open(a)} style={s.result}><Image source={{uri:a.img}} style={s.resultImg}/><View style={{flex:1}}><Text style={s.eyebrow}>{a.cat.toUpperCase()}</Text><Text style={s.resultTitle}>{a.title}</Text><Text style={s.time}>{a.time} de leitura</Text></View></Pressable>)}</ScrollView></SafeAreaView>}

function Saved({saved,open}){const list=news.filter(a=>saved.includes(a.id));return <SafeAreaView style={s.root}><StatusBar barStyle="dark-content"/><ScrollView contentContainerStyle={s.page}><Text style={s.screenTitle}>Salvos</Text><Text style={s.subtitle}>Suas matérias para ler depois.</Text>{list.length===0?<View style={s.empty}><Text style={s.emptyTitle}>Nenhuma matéria salva.</Text><Text style={s.muted}>Toque no coração de uma notícia para guardá-la aqui.</Text></View>:list.map(a=><Pressable key={a.id} onPress={()=>open(a)} style={s.saved}><Image source={{uri:a.img}} style={s.savedImg}/><Text style={s.savedTitle}>{a.title}</Text></Pressable>)}</ScrollView></SafeAreaView>}

function Profile({user,logout}){return <SafeAreaView style={s.root}><StatusBar barStyle="dark-content"/><ScrollView contentContainerStyle={s.page}><Text style={s.screenTitle}>Perfil</Text><View style={s.profile}><View style={s.avatar}><Text style={s.avatarText}>{user.name[0].toUpperCase()}</Text></View><Text style={s.profileName}>{user.name}</Text><Text style={s.muted}>{user.email}</Text></View><View style={s.settings}><View style={s.setting}><Text>Notificações</Text><Text style={s.muted}>Ativas</Text></View><View style={s.setting}><Text>Tema</Text><Text style={s.muted}>Claro</Text></View></View><Pressable onPress={logout} style={s.logout}><Text style={s.logoutText}>Sair da conta</Text></Pressable></ScrollView></SafeAreaView>}

function Article({a,saved,toggle,close}){return <SafeAreaView style={s.article}><StatusBar barStyle="light-content"/><ScrollView><View style={s.articleHero}><Image source={{uri:a.img}} style={s.heroImg}/><View style={s.overlay}/><Pressable onPress={close} style={s.back}><Text style={s.backText}>‹</Text></Pressable><View style={s.articleHead}><Text style={s.eyebrowLight}>{a.cat.toUpperCase()}</Text><Text style={s.articleTitle}>{a.title}</Text><Text style={s.timeLight}>{a.time} de leitura</Text></View></View><View style={s.articleBody}><View style={s.articleTop}><Text style={s.lead}>{a.desc}</Text><Heart active={saved.includes(a.id)} onPress={()=>toggle(a.id)}/></View><Text style={s.paragraph}>Esta matéria é demonstrativa e já está estruturada para receber conteúdo editorial real. O aplicativo organiza as notícias por categoria e deixa o leitor decidir o que merece atenção.</Text><Text style={s.paragraph}>Quando uma API for conectada, títulos, autores, horários, imagens e links poderão vir diretamente do backend sem mudar a experiência principal.</Text></View></ScrollView></SafeAreaView>}

export default function App(){const[user,setUser]=useState(null),[tab,setTab]=useState('home'),[saved,setSaved]=useState([]),[cat,setCat]=useState('Para você'),[article,setArticle]=useState(null);const toggle=id=>setSaved(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]);if(!user)return <Login onLogin={setUser}/>;if(article)return <Article a={article} saved={saved} toggle={toggle} close={()=>setArticle(null)}/>;const screen={home:<Home user={user} saved={saved} toggle={toggle} open={setArticle} cat={cat} setCat={setCat}/>,search:<Search open={setArticle}/>,saved:<Saved saved={saved} open={setArticle}/>,profile:<Profile user={user} logout={()=>setUser(null)}/>[tab];return <View style={s.app}>{screen}<Tabs tab={tab} setTab={setTab}/></View>}

const s=StyleSheet.create({
app:{flex:1,backgroundColor:C.bg},root:{flex:1,backgroundColor:C.bg},page:{padding:20,paddingBottom:110},
logoRow:{flexDirection:'row',alignItems:'center',gap:8},mark:{width:31,height:31,borderRadius:7,backgroundColor:C.ink,alignItems:'center',justifyContent:'center'},markText:{color:'#fff',fontSize:19,fontWeight:'900'},logo:{fontSize:24,fontWeight:'900',letterSpacing:-1.5,color:C.ink},
login:{flex:1,backgroundColor:C.bg},loginBox:{padding:28,paddingTop:50,flexGrow:1},kicker:{fontSize:10,fontWeight:'900',letterSpacing:2,color:C.muted,marginTop:13,marginBottom:70},loginTitle:{fontSize:38,lineHeight:42,fontWeight:'900',letterSpacing:-1.5,color:C.ink},loginDesc:{fontSize:16,lineHeight:24,color:C.muted,marginTop:12,marginBottom:30},form:{gap:12},input:{height:56,borderWidth:1,borderColor:C.line,borderRadius:14,backgroundColor:C.white,paddingHorizontal:17,fontSize:16,color:C.ink},error:{color:C.red,fontSize:13},primary:{height:56,borderRadius:14,backgroundColor:C.ink,alignItems:'center',justifyContent:'center'},primaryText:{color:'#fff',fontSize:16,fontWeight:'800'},switch:{height:50,alignItems:'center',justifyContent:'center'},switchText:{color:C.red,fontWeight:'800'},note:{marginTop:30,paddingTop:30,textAlign:'center',color:'#9A968E',fontSize:12},
header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',marginBottom:22},greet:{fontSize:13,color:C.muted,marginBottom:5},headerTitle:{fontSize:27,lineHeight:31,fontWeight:'900',letterSpacing:-1,maxWidth:230},chips:{gap:8,paddingBottom:18},chip:{borderWidth:1,borderColor:C.line,backgroundColor:C.white,borderRadius:30,paddingHorizontal:15,paddingVertical:9},chipOn:{backgroundColor:C.ink,borderColor:C.ink},chipText:{fontSize:13,fontWeight:'700',color:C.muted},chipTextOn:{color:'#fff'},
hero:{height:420,borderRadius:22,overflow:'hidden',backgroundColor:C.ink,marginBottom:28},heroImg:{...StyleSheet.absoluteFillObject,width:'100%',height:'100%'},overlay:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(0,0,0,.52)'},heroText:{position:'absolute',left:22,right:22,bottom:24},heroHeart:{position:'absolute',right:14,top:14,backgroundColor:'rgba(255,255,255,.2)',borderRadius:25},eyebrowLight:{color:'#E8E2D8',fontSize:10,fontWeight:'900',letterSpacing:1.5,marginBottom:9},heroTitle:{color:'#fff',fontSize:29,lineHeight:33,fontWeight:'900',letterSpacing:-1},heroDesc:{color:'#E6E3DD',fontSize:14,lineHeight:20,marginTop:9},timeLight:{color:'#D2CEC6',fontSize:11,marginTop:10,fontWeight:'600'},
section:{flexDirection:'row',justifyContent:'space-between',alignItems:'baseline',marginBottom:12},sectionTitle:{fontSize:21,fontWeight:'900',letterSpacing:-.6,color:C.ink},muted:{color:C.muted,fontSize:12},card:{flexDirection:'row',alignItems:'center',backgroundColor:C.white,borderRadius:17,padding:10,marginBottom:11,borderWidth:1,borderColor:'#ECE8E1'},cardImg:{width:91,height:106,borderRadius:12},cardBody:{flex:1,paddingHorizontal:12},eyebrow:{color:C.red,fontSize:9,fontWeight:'900',letterSpacing:1.4,marginBottom:5},cardTitle:{color:C.ink,fontSize:15,lineHeight:19,fontWeight:'800'},cardDesc:{color:C.muted,fontSize:11,lineHeight:16,marginTop:5},time:{color:'#9A968E',fontSize:10,marginTop:7,fontWeight:'600'},heart:{width:36,height:38,alignItems:'center',justifyContent:'center'},
tabs:{position:'absolute',left:12,right:12,bottom:12,height:66,borderRadius:22,backgroundColor:C.white,borderWidth:1,borderColor:C.line,flexDirection:'row',alignItems:'center',justifyContent:'space-around',elevation:7,shadowColor:'#000',shadowOpacity:.08,shadowRadius:16},tab:{width:70,alignItems:'center'},tabIcon:{fontSize:22,lineHeight:25,color:'#9A968E'},tabLabel:{fontSize:10,fontWeight:'700',color:'#9A968E',marginTop:2},active:{color:C.ink},
screenTitle:{fontSize:34,fontWeight:'900',letterSpacing:-1.2,color:C.ink,marginTop:8},subtitle:{color:C.muted,fontSize:15,marginTop:5,marginBottom:22},search:{height:56,borderRadius:15,backgroundColor:C.white,borderWidth:1,borderColor:C.line,flexDirection:'row',alignItems:'center',paddingHorizontal:15,marginVertical:18},searchIcon:{fontSize:25,color:C.muted,marginRight:8},searchInput:{flex:1,fontSize:16,color:C.ink},result:{flexDirection:'row',gap:13,paddingVertical:14,borderBottomWidth:1,borderBottomColor:C.line},resultImg:{width:92,height:84,borderRadius:12},resultTitle:{color:C.ink,fontSize:15,lineHeight:19,fontWeight:'800',marginTop:2},
empty:{marginTop:28,padding:25,borderRadius:18,backgroundColor:C.soft},emptyTitle:{fontSize:18,fontWeight:'900',color:C.ink,marginBottom:7},saved:{flexDirection:'row',gap:14,backgroundColor:C.white,padding:11,borderRadius:16,marginBottom:12,borderWidth:1,borderColor:C.line},savedImg:{width:100,height:92,borderRadius:11},savedTitle:{flex:1,color:C.ink,fontSize:15,lineHeight:20,fontWeight:'800'},
profile:{backgroundColor:C.white,borderRadius:20,borderWidth:1,borderColor:C.line,alignItems:'center',padding:28,marginTop:20},avatar:{width:76,height:76,borderRadius:38,backgroundColor:C.ink,alignItems:'center',justifyContent:'center',marginBottom:13},avatarText:{color:'#fff',fontSize:29,fontWeight:'900'},profileName:{color:C.ink,fontSize:21,fontWeight:'900',marginBottom:5},settings:{marginTop:13,backgroundColor:C.white,borderRadius:18,borderWidth:1,borderColor:C.line,paddingHorizontal:18},setting:{flexDirection:'row',justifyContent:'space-between',paddingVertical:18,borderBottomWidth:1,borderBottomColor:C.line},logout:{height:53,borderRadius:14,borderWidth:1,borderColor:'#D8D0C8',alignItems:'center',justifyContent:'center',marginTop:18},logoutText:{color:C.red,fontWeight:'800'},
article:{flex:1,backgroundColor:C.white},articleHero:{height:490,backgroundColor:C.ink},back:{position:'absolute',top:15,left:17,width:42,height:42,borderRadius:21,backgroundColor:'rgba(0,0,0,.35)',alignItems:'center',justifyContent:'center'},backText:{color:'#fff',fontSize:36,lineHeight:38,marginTop:-3},articleHead:{position:'absolute',left:22,right:22,bottom:30},articleTitle:{color:'#fff',fontSize:31,lineHeight:36,fontWeight:'900',letterSpacing:-1},articleBody:{padding:22,paddingBottom:60},articleTop:{flexDirection:'row',alignItems:'flex-start'},lead:{flex:1,color:C.ink,fontSize:18,lineHeight:27,fontWeight:'700'},paragraph:{color:'#45413C',fontSize:16,lineHeight:27,marginTop:25}
});